name: "Chromatic"

on:
  # push
    # branches:
    #   - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    # ref: ${{ github.event.pull_request.head.ref }}
    # types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0+sha256.7a4261e50d9a44d9240baf6c9d6e10089dcf0a79d0007f2a26985a6927324177
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Enable turbosnap to detect changed components
          onlyChanged: true
          exitZeroOnChanges: true
          # autoAcceptChanges: true